# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripId', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tripsUser',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tripsUser',
                'managed': True,
            },
        ),
    ]
