# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trips_tripsuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripsuser',
            options={'managed': False},
        ),
    ]
