# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171115_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': False},
        ),
    ]
